version: "3.8"

services:
  psql-db:
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=89194161213
    build:
      context: .
      dockerfile: ./devops/db/Dockerfile
    ports:
      - '5432:5432'

  backend:
    container_name: backend-app-cont
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8189'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/office_app_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=89194161213
    depends_on:
      - psql-db



